name: Cypress User Journey Night run

on:
  schedule:
  #midnight
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Start app in background
        run: npm start & npx wait-on http://localhost:3000

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          spec: cypress/e2e/user-journey.cy.ts
          browser: chrome
          
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          
      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          
      #----implement notifications in slack-------
      # - name: Slack notification on failure
      #   uses: 8398a7/action-slack@v3
      #   if: failure()
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,workflow
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}